project_id = "nrrgqnruoylwztddkntm"

[functions.firecrawl-scrape]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.firecrawl-map]
verify_jwt = false

[functions.firecrawl-crawl]
verify_jwt = false

[functions.send-lead-confirmation]
verify_jwt = false

[functions.og-image]
verify_jwt = false